"""Report generation in multiple formats."""

from __future__ import annotations

import json
from datetime import datetime
from typing import Any

from .analysis import MetricTrend, HealthScore


def format_value(value: float | None, unit: str = "") -> str:
    if value is None:
        return "N/A"
    if unit == "$":
        return f"${value:,.2f}"
    elif unit == "#":
        return f"{value:,.0f}"
    elif unit == "%":
        return f"{value:.1f}%"
    return f"{value:,.2f}"


def generate_terminal_report(
    trends: dict[str, MetricTrend],
    health: HealthScore,
    flags: list[str],
    recommendations: list[str],
    project_name: str = "",
    date_range: str = "",
) -> str:
    """Generate a rich terminal-friendly report."""
    lines = []
    lines.append("=" * 60)
    lines.append(f"  RC PULSE — Subscription Health Report")
    if project_name:
        lines.append(f"  Project: {project_name}")
    if date_range:
        lines.append(f"  Period: {date_range}")
    lines.append(f"  Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append("=" * 60)
    lines.append("")

    # Health Score
    lines.append(f"  PULSE SCORE: {health.overall:.0f}/100 {health.grade_emoji} (Grade: {health.grade})")
    lines.append("")
    lines.append("  Dimensions:")
    for dim in ["growth", "retention", "conversion", "revenue_quality", "momentum"]:
        val = getattr(health, dim)
        bar_len = int(val / 5)
        bar = "█" * bar_len + "░" * (20 - bar_len)
        lines.append(f"    {dim.replace('_', ' ').title():20s} [{bar}] {val:.0f}")
    lines.append("")

    # Metric Summary
    lines.append("─" * 60)
    lines.append("  KEY METRICS")
    lines.append("─" * 60)
    for name, trend in trends.items():
        change_str = ""
        if trend.period_change is not None:
            arrow = "↑" if trend.period_change >= 0 else "↓"
            change_str = f" ({arrow} {abs(trend.period_change):.1f}%)"
        lines.append(
            f"  {trend.trend_emoji} {trend.display_name:30s} "
            f"{format_value(trend.current, trend.unit):>12s}{change_str}"
        )
    lines.append("")

    # Risk Flags
    if flags:
        lines.append("─" * 60)
        lines.append("  ⚠️  RISK FLAGS")
        lines.append("─" * 60)
        for flag in flags:
            lines.append(f"  • {flag}")
        lines.append("")

    # Recommendations
    if recommendations:
        lines.append("─" * 60)
        lines.append("  💡 RECOMMENDATIONS")
        lines.append("─" * 60)
        for rec in recommendations:
            lines.append(f"  {rec}")
            lines.append("")

    lines.append("=" * 60)
    lines.append("  Generated by RC Pulse — https://github.com/CleoSterlingAI/rc-pulse")
    lines.append("=" * 60)

    return "\n".join(lines)


def generate_markdown_report(
    trends: dict[str, MetricTrend],
    health: HealthScore,
    flags: list[str],
    recommendations: list[str],
    project_name: str = "",
    date_range: str = "",
) -> str:
    """Generate a Markdown formatted report."""
    lines = []
    lines.append("# RC Pulse — Subscription Health Report")
    lines.append("")
    if project_name:
        lines.append(f"**Project:** {project_name}")
    if date_range:
        lines.append(f"**Period:** {date_range}")
    lines.append(f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M')}")
    lines.append("")

    # Health Score
    lines.append(f"## Pulse Score: {health.overall:.0f}/100 {health.grade_emoji}")
    lines.append("")
    lines.append("| Dimension | Score |")
    lines.append("|-----------|-------|")
    for dim in ["growth", "retention", "conversion", "revenue_quality", "momentum"]:
        val = getattr(health, dim)
        lines.append(f"| {dim.replace('_', ' ').title()} | {val:.0f}/100 |")
    lines.append("")

    # Metrics
    lines.append("## Key Metrics")
    lines.append("")
    lines.append("| Metric | Current | Change | Trend |")
    lines.append("|--------|---------|--------|-------|")
    for name, trend in trends.items():
        change = f"{trend.period_change:+.1f}%" if trend.period_change is not None else "N/A"
        lines.append(
            f"| {trend.display_name} | {format_value(trend.current, trend.unit)} "
            f"| {change} | {trend.trend_emoji} {trend.trend_direction} |"
        )
    lines.append("")

    # Trend Details
    lines.append("## Metric Details")
    lines.append("")
    for name, trend in trends.items():
        lines.append(f"### {trend.display_name}")
        direction, count = trend.consecutive_direction
        lines.append(f"- **Current:** {format_value(trend.current, trend.unit)}")
        lines.append(f"- **Mean:** {format_value(trend.mean, trend.unit)}")
        if trend.std_dev is not None:
            lines.append(f"- **Std Dev:** {format_value(trend.std_dev, trend.unit)}")
        lines.append(f"- **Trend:** {trend.trend_emoji} {trend.trend_direction}")
        lines.append(f"- **Consecutive {direction}s:** {count}")
        lines.append("")

    # Risk Flags
    if flags:
        lines.append("## ⚠️ Risk Flags")
        lines.append("")
        for flag in flags:
            lines.append(f"- {flag}")
        lines.append("")

    # Recommendations
    if recommendations:
        lines.append("## 💡 Recommendations")
        lines.append("")
        for rec in recommendations:
            lines.append(f"- {rec}")
        lines.append("")

    lines.append("---")
    lines.append("*Generated by [RC Pulse](https://github.com/CleoSterlingAI/rc-pulse)*")

    return "\n".join(lines)


def generate_json_report(
    trends: dict[str, MetricTrend],
    health: HealthScore,
    flags: list[str],
    recommendations: list[str],
    project_name: str = "",
    date_range: str = "",
) -> str:
    """Generate a JSON report."""
    report = {
        "meta": {
            "project": project_name,
            "period": date_range,
            "generated_at": datetime.now().isoformat(),
            "tool": "rc-pulse",
            "version": "0.1.0",
        },
        "health_score": health.to_dict(),
        "metrics": {
            name: {
                "display_name": t.display_name,
                "current": t.current,
                "previous": t.previous,
                "period_change_pct": round(t.period_change, 2) if t.period_change else None,
                "mean": round(t.mean, 2) if t.mean else None,
                "trend": t.trend_direction,
                "unit": t.unit,
                "values": list(zip(t.dates, t.values)),
            }
            for name, t in trends.items()
        },
        "risk_flags": flags,
        "recommendations": recommendations,
    }
    return json.dumps(report, indent=2)


HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>RC Pulse — {project_name}</title>
<style>
  :root {{ --bg: #0d1117; --card: #161b22; --border: #30363d; --text: #c9d1d9;
           --accent: #58a6ff; --green: #3fb950; --yellow: #d29922; --red: #f85149; }}
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
          background: var(--bg); color: var(--text); padding: 2rem; line-height: 1.6; }}
  .container {{ max-width: 900px; margin: 0 auto; }}
  h1 {{ color: var(--accent); margin-bottom: 0.5rem; }}
  .meta {{ color: #8b949e; margin-bottom: 2rem; }}
  .score-card {{ background: var(--card); border: 1px solid var(--border); border-radius: 12px;
                 padding: 2rem; margin-bottom: 2rem; text-align: center; }}
  .score-number {{ font-size: 4rem; font-weight: bold; color: var(--accent); }}
  .score-grade {{ font-size: 1.5rem; margin-top: 0.5rem; }}
  .dimensions {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
                 gap: 1rem; margin-top: 1.5rem; }}
  .dim {{ background: var(--bg); border-radius: 8px; padding: 1rem; text-align: center; }}
  .dim-label {{ font-size: 0.8rem; text-transform: uppercase; color: #8b949e; }}
  .dim-value {{ font-size: 1.5rem; font-weight: bold; margin-top: 0.25rem; }}
  .metrics-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
                   gap: 1rem; margin-bottom: 2rem; }}
  .metric {{ background: var(--card); border: 1px solid var(--border); border-radius: 8px;
             padding: 1.5rem; }}
  .metric-name {{ font-size: 0.85rem; color: #8b949e; text-transform: uppercase; }}
  .metric-value {{ font-size: 1.8rem; font-weight: bold; margin: 0.5rem 0; }}
  .metric-change {{ font-size: 0.9rem; }}
  .metric-change.positive {{ color: var(--green); }}
  .metric-change.negative {{ color: var(--red); }}
  .section {{ background: var(--card); border: 1px solid var(--border); border-radius: 12px;
              padding: 1.5rem; margin-bottom: 1.5rem; }}
  .section h2 {{ color: var(--accent); margin-bottom: 1rem; font-size: 1.2rem; }}
  .flag {{ padding: 0.75rem; background: rgba(248, 81, 73, 0.1); border-left: 3px solid var(--red);
           margin-bottom: 0.5rem; border-radius: 0 4px 4px 0; }}
  .rec {{ padding: 0.75rem; background: rgba(88, 166, 255, 0.1); border-left: 3px solid var(--accent);
          margin-bottom: 0.5rem; border-radius: 0 4px 4px 0; }}
  .footer {{ text-align: center; color: #8b949e; margin-top: 2rem; padding-top: 1rem;
             border-top: 1px solid var(--border); }}
  .footer a {{ color: var(--accent); text-decoration: none; }}
</style>
</head>
<body>
<div class="container">
  <h1>📊 RC Pulse</h1>
  <p class="meta">{project_name} &middot; {date_range} &middot; Generated {generated_at}</p>
  
  <div class="score-card">
    <div class="score-number">{overall_score}</div>
    <div class="score-grade">{grade_emoji} Grade {grade}</div>
    <div class="dimensions">
      {dimension_html}
    </div>
  </div>

  <div class="metrics-grid">
    {metrics_html}
  </div>

  {flags_html}
  {recs_html}

  <div class="footer">
    Generated by <a href="https://github.com/CleoSterlingAI/rc-pulse">RC Pulse</a> 
    &middot; Built by <a href="https://twitter.com/CleoSterlingAI">Cleo Sterling</a>
  </div>
</div>
</body>
</html>"""


def generate_html_report(
    trends: dict[str, MetricTrend],
    health: HealthScore,
    flags: list[str],
    recommendations: list[str],
    project_name: str = "",
    date_range: str = "",
) -> str:
    """Generate an HTML report."""
    dim_html = ""
    for dim in ["growth", "retention", "conversion", "revenue_quality", "momentum"]:
        val = getattr(health, dim)
        dim_html += f'<div class="dim"><div class="dim-label">{dim.replace("_", " ").title()}</div><div class="dim-value">{val:.0f}</div></div>\n'

    metrics_html = ""
    for name, trend in trends.items():
        change_class = ""
        change_str = "N/A"
        if trend.period_change is not None:
            change_class = "positive" if trend.period_change >= 0 else "negative"
            arrow = "↑" if trend.period_change >= 0 else "↓"
            change_str = f"{arrow} {abs(trend.period_change):.1f}%"
        metrics_html += f'''<div class="metric">
  <div class="metric-name">{trend.display_name}</div>
  <div class="metric-value">{format_value(trend.current, trend.unit)}</div>
  <div class="metric-change {change_class}">{change_str} {trend.trend_emoji}</div>
</div>\n'''

    flags_html = ""
    if flags:
        flags_items = "\n".join(f'<div class="flag">{f}</div>' for f in flags)
        flags_html = f'<div class="section"><h2>⚠️ Risk Flags</h2>{flags_items}</div>'

    recs_html = ""
    if recommendations:
        recs_items = "\n".join(f'<div class="rec">{r}</div>' for r in recommendations)
        recs_html = f'<div class="section"><h2>💡 Recommendations</h2>{recs_items}</div>'

    return HTML_TEMPLATE.format(
        project_name=project_name,
        date_range=date_range,
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M"),
        overall_score=f"{health.overall:.0f}",
        grade=health.grade,
        grade_emoji=health.grade_emoji,
        dimension_html=dim_html,
        metrics_html=metrics_html,
        flags_html=flags_html,
        recs_html=recs_html,
    )
