#!/usr/bin/env python3
"""Replay pre-recorded RC Pulse output with realistic typing effect."""
import sys
import time

OUTPUT = """📡 Connected to project: Dark Noise
📊 Fetching 8 charts (rate limited to 5/min)...
  [1/8] Fetching revenue...
  [2/8] Fetching mrr...
  [3/8] Fetching actives...
  [4/8] Fetching churn...
  [5/8] Fetching trial_conversion_rate...
  [6/8] Fetching customers_new...
  [7/8] Fetching trials...
  [8/8] Fetching refund_rate...

============================================================
  RC PULSE — Subscription Health Report
  Project: Dark Noise
  Period: 2025-01-01 → 2026-03-18
  Generated: 2026-03-18 12:48
============================================================

  PULSE SCORE: 58/100 🟠 (Grade: C)

  Dimensions:
    Growth               [█████████░░░░░░░░░░░] 47
    Retention            [█████░░░░░░░░░░░░░░░] 25
    Conversion           [████████████████████] 100
    Revenue Quality      [███████████████░░░░░] 80
    Momentum             [██████████░░░░░░░░░░] 52

────────────────────────────────────────────────────────────
  KEY METRICS
────────────────────────────────────────────────────────────
  ➡️ Revenue                           $3,227.71 (↓ 30.1%)
  ➡️ MRR                               $4,536.72 (↓ 0.6%)
  ➡️ Active Subscriptions                  2,521 (↓ 0.6%)
  ➡️ Churn                                 2,537 (↑ 0.1%)
  ➡️ Trial Conversion Rate                   161 (↓ 37.6%)
  📉 New Customers                         1,076 (↓ 43.5%)
  ➡️ Active Trials                            77 (↑ 32.8%)
  ➡️ Refund Rate                             241 (↓ 30.1%)

────────────────────────────────────────────────────────────
  ⚠️  RISK FLAGS
────────────────────────────────────────────────────────────
  • Revenue dropped 30.1% last period
  • Trial Conversion Rate dropped 37.6% last period
  • New Customers dropped 43.5% last period
  • Active Trials shows high volatility (CV=37.8%)
  • Refund Rate dropped 30.1% last period

────────────────────────────────────────────────────────────
  💡 RECOMMENDATIONS
────────────────────────────────────────────────────────────
  🔴 **Retention needs attention.** Consider implementing win-back campaigns, improving onboarding, or surveying churned users to identify pain points.

  📉 **Growth is stalling.** Evaluate your acquisition channels, consider A/B testing paywalls, and explore new markets or platforms.

============================================================
  Generated by RC Pulse — https://github.com/ohmanthatsgreat/rc-pulse
============================================================"""

for line in OUTPUT.split("\n"):
    # Simulate fetching delay for API calls
    if line.strip().startswith("[") and "Fetching" in line:
        time.sleep(0.3)
    print(line)
    sys.stdout.flush()
    time.sleep(0.05)

if __name__ == "__main__":
    pass
